name: release

on:
  pull_request:
    types: [closed]

jobs:

  create-release:
    name: create release
    runs-on: ubuntu-18.04
    if: startsWith( github.event.pull_request.title , 'release' ) && github.event.pull_request.merged

    steps:
      -
        name: checkout
        uses: actions/checkout@v2

      -
        name: calculate release level
        id: level
        env:
          RELEASE_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "::set-output name=value::$(echo ${RELEASE_TITLE} | cut -d '/' -f2)"

      -
        name: current version
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: current-version

      -
        name: "calculate next version (from: ${{ steps.current-version.outputs.tag }}, with-update: ${{ steps.level.outputs.value }})"
        id: next-version
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.current-version.outputs.tag }}
          level: ${{ steps.level.outputs.value }}

      -
        name: push tag
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.next-version.outputs.new_version }}
          message: "Release version ${{ steps.next-version.outputs.new_version }}"

      - name: project version
        id: projectVersion
        run: echo "::set-output name=version::$(echo $NEW_VERSION)"
        env:
          NEW_VERSION: ${{ steps.next-version.outputs.new_version }}

      - name: create release
        id: release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.projectVersion.outputs.version }}
          release_name: Release ${{ steps.projectVersion.outputs.version }}
          draft: false
          prerelease: false

      - name: file release url
        run: |
          echo "$PROJECT_VERSION" >> release.txt
          echo "$RELEASE_ID" >> release.txt
          echo "$RELEASE_URL" >> release.txt
        env:
          PROJECT_VERSION: ${{ steps.projectVersion.outputs.version }}
          RELEASE_URL: ${{ steps.release.outputs.upload_url }}
          RELEASE_ID: ${{ steps.release.outputs.id }}

      - name: store release url
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: release.txt

  upload-release:
    name: (${{ matrix.os }}) upload release
    needs: create-release
    strategy:
      matrix:
        os: [macos, ubuntu]
    runs-on:  ${{ matrix.os }}-latest

    steps:
      -
        name: checkout
        uses: actions/checkout@v1

      -
        name: setup GraalVM
        uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: "20.0.0.java11"

      -
        name: install native-image
        run: gu install native-image

      -
        name: download release url
        uses: actions/download-artifact@v1
        with:
          name: release

      -
        name: configure release url
        id: config
        run: |
          version=`head -n 1 release/release.txt`
          url=`tail -n 1 release/release.txt`
          echo "::set-output name=projectVersion::${version}"
          echo "::set-output name=releaseUrl::${url}"

      -
        name: cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('build.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-

      -
        name: "build application version: ${{ steps.config.outputs.projectVersion }}"
        run: ./gradlew zipNativeImage
        env:
         RUNNING_OS: ${{ matrix.os }}
         PROJECT_VERSION: ${{ steps.config.outputs.projectVersion }}

      -
        name: "upload release for ${{ matrix.os }}, version: ${{ steps.config.outputs.projectVersion }}"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.config.outputs.releaseUrl }}
          asset_path: ./build/release/instant-${{ matrix.os }}-${{ steps.config.outputs.projectVersion }}.zip
          asset_name: instant-${{ matrix.os }}.zip
          asset_content_type: application/zip

  delete-artifact:
    name: delete artifact
    needs: upload-release
    runs-on: ubuntu-18.04

    steps:
      -
        name: get artifacts id
        id: artifactId
        run: |
          id=$(
            curl -H "Authorization: token ${TOKEN}" "https://api.github.com/repos/mike-neck/instant/actions/runs/${RUN_ID}/artifacts" |
              jq -r '[.artifacts[]] | map(select( .["name"] == "release")) | .[].id' |
              head -n 1)
          echo "::set-output name=value::${id}"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}

      -
        name: delete artifact
        run: |
          curl -X DELETE \
            -H "Authorization: token ${TOKEN}" \
            "https://api.github.com/repos/mike-neck/instant/actions/artifacts/${ARTIFACT_ID}"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_ID: ${{ steps.artifactId.outputs.value }}
