name: add new tag

on:
  pull_request:
    types: [closed]

jobs:
  add-tag:
    runs-on: ubuntu-18.04
    if: startsWith( github.event.pull_request.title , 'release' )

    steps:
      -
        name: show event
        run: echo "${EVENT}"
        env:
          EVENT: ${{ toJson(github.event) }}

      -
        name: checkout
        uses: actions/checkout@v2

      -
        name: calculate release level
        id: level
        env:
          RELEASE_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "set-output name=value::$(echo ${RELEASE_TITLE} | cut -d '/' -f2)"

      -
        name: current version
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: current-version

      -
        name: calculate next version
        id: next-version
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.current-version.outputs.tag }}
          level: ${{ steps.level.outputs.value }}

      -
        name: push tag
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.next-version.outputs.new_version }}
          message: "Release version ${{ steps.next-version.outputs.new_version }}"
